version: 2
jobs:
  build:
    docker:
      - image: docker:17.06.0-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t reiniergs/circleci-centos7-jdk-node8-browsers:circle .
      - deploy:
          name: Tag docker images
          command: |
            docker tag reiniergs/circleci-centos7-jdk-node8-browsers:circle reiniergs/circleci-centos7-jdk-node8-browsers:latest
      - deploy:
          name: Login to Docker Hub
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - deploy:
          name: Push docker images
          command: |
            docker push reiniergs/circleci-centos7-jdk-node8-browsers:latest

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
            context: org-global
